# Generated by Django 4.2.1 on 2023-05-25 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_pedido_id_alter_pedido_codigo_seguimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='direccion_envio',
            field=models.CharField(blank=True, max_length=70, verbose_name='Direccion del pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En progreso', 'En progreso'), ('Completado', 'Completado')], default='Pendiente', max_length=20, verbose_name='Estado del Pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha actualizada'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('Debito', 'Debito'), ('Credito', 'Credito'), ('Transferencia', 'Transferencia')], max_length=100, verbose_name='Metodo de Pago'),
        ),
    ]
