# Generated by Django 4.2.1 on 2023-05-31 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_pedido_direccion_envio_alter_pedido_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='producto',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
