# Generated by Django 4.2.1 on 2023-06-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_producto_remove_pedido_producto_pedido_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('En preparacion', 'En preparacion'), ('En camino', 'En camino'), ('Completado', 'Completado')], default='Pendiente', max_length=20, verbose_name='Estado del Pedido'),
        ),
    ]
