# Generated by Django 4.2.1 on 2023-06-15 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_pedido_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_seguimiento', models.CharField(max_length=50)),
                ('nombre_origen', models.CharField(max_length=100)),
                ('direccion_origen', models.CharField(max_length=200)),
                ('nombre_destino', models.CharField(max_length=100)),
                ('direccion_destino', models.CharField(max_length=200)),
                ('comentario', models.CharField(max_length=200)),
                ('info', models.CharField(max_length=200)),
            ],
        ),
    ]
