# Generated by Django 4.2.1 on 2023-06-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_pedidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='estado',
            field=models.CharField(choices=[('En preparacion', 'En preparacion'), ('En camino', 'En camino'), ('Completado', 'Completado')], default='Pendiente', max_length=20, verbose_name='Estado del Pedido'),
        ),
    ]
