# Generated by Django 4.2.1 on 2023-06-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_pedidos_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='id',
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='codigo_seguimiento',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='estado',
            field=models.CharField(choices=[('En preparacion', 'En preparacion'), ('En camino', 'En camino'), ('Completado', 'Completado')], default='En preparacion', max_length=20, verbose_name='Estado del Pedido'),
        ),
    ]
