# Generated by Django 4.2.1 on 2023-06-16 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_pedidos_id_alter_pedidos_codigo_seguimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='info',
        ),
    ]
