# Generated by Django 4.2.1 on 2023-06-18 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_pedidos_comentario_remove_pedidos_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidos',
            old_name='nombre_origen',
            new_name='nombre_conductor',
        ),
    ]
