# Generated by Django 4.2.1 on 2023-06-19 17:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_pedido_fecha_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_pedido',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='fecha_pedido',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del Pedido'),
        ),
    ]
