# Generated by Django 4.2.1 on 2023-06-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_pedido_fecha_pedido_pedidos_fecha_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='correo_destino',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
