# Generated by Django 4.2.1 on 2023-07-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_pedidos_fecha_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='direccion_origen',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='lugar_origen',
            field=models.CharField(choices=[('Bodega', 'Bodega'), ('Sucursal', 'Sucursal')], default='Bodega', max_length=20, verbose_name='Lugar de origen'),
        ),
    ]
