# Generated by Django 4.2.1 on 2023-07-05 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_pedidos_direccion_origen_pedidos_lugar_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='direccion_origen',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='nombre_origen',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='direccion_destino',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='nombre_conductor',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='nombre_destino',
            field=models.CharField(default='', max_length=100),
        ),
    ]
